[package]
name = "train"
version = "0.1.0"
edition = "2021"

[dependencies]
statrs = "0.18"
rand = "0.9"
rand_distr = "0.5"
interp = "2.0"
rayon = "1.10"
nlopt = "0.8"
serde_json = "1.0"
serde = { version = "1.0.219", features = ["derive"] }
csv = "1.3"

[lib]
name = "lib"
path = "src/lib.rs"
